### ISSUE TITLE
First video does not record

### ISSUE THREAD

**Issue by vshie** [bluerobotics/qgroundcontrol#107]
On MacOS with latest QGC BR build - for multiple deployments I've run into this issue, and chalked it up to my own forgetfulness. If the video folder is empty, and a recording is started and stopped, it does not save. Recordings started at any point afterwards do save. 

Thanks!

**Comment by jaxxzer** [comment]
Can not reproduce on v3.2.4-BlueRobotics-Rev2 on windows, mac or linux. Can you please confirm?

**Comment by jaxxzer** [comment]
Closing this. Let me know if it comes up again @vshie.
