### ISSUE TITLE
Text overflow on default frame params button.

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/qgroundcontrol#12]

**Comment by jaxxzer** [comment]
![capture](https://user-images.githubusercontent.com/8315108/27208400-4e4acdfa-51fa-11e7-890f-28651814e062.PNG)

**Comment by dheideman** [comment]
Addressed in [pr-text-overflow-frame-params](https://github.com/bluerobotics/qgroundcontrol/tree/pr-text-overflow-frame-params).

**Comment by jaxxzer** [comment]
https://github.com/mavlink/qgroundcontrol/pull/5661
