### ISSUE TITLE
Add dive information in video

### ISSUE THREAD

**Issue by patrickelectric** [bluerobotics/qgroundcontrol#122]
It's possible to use `textoverlay` to add log information with video while recording, similar to #32.
[Ref.](http://discuss.bluerobotics.com/t/picture-freeze-while-running-screen-recorder/1718/3?u=patrickelectric)

**Comment by patrickelectric** [comment]
@jaxxzer what you think about that ?

**Comment by jaxxzer** [comment]
I've done this: https://github.com/bluerobotics/qgroundcontrol/tree/pr-video-text-overlay

It uses a ton of CPU to re-encode the video, so this implementation at least is not practical for most laptops.

**Comment by patrickelectric** [comment]
76e9baa CPU problem solved, I'll send a PR ASAP :)

**Comment by jaxxzer** [comment]
There was still some issue with this, the encoder is required to embed the text in the video, which required the high cpu use.

**Comment by Williangalvani** [comment]
Note: We decided subtitles (advanced substation alpha subtitles) are the best approach to overlay data on video without re-encoding and still allowing to turn the overlay on/off.
The discussion is now taking place [here](https://github.com/mavlink/qgroundcontrol/issues/7286)
