### ISSUE TITLE
NSH shell connection drops after reboot.

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/qgroundcontrol#129]
Makes it impossible to view boot diagnostics. MAVProxy has implemented the desired behavior.

**Comment by patrickelectric** [comment]
Done in: https://github.com/mavlink/qgroundcontrol/issues/3881

**Comment by jaxxzer** [comment]
> Done in: mavlink#3881

This patch added the feature. There is a problem with the feature, that is what this issue pertains to. If you send a reboot to the nsh shell, you are no longer in nsh shell after reboot. Mavproxy will keep you in nsh shell as desired, so it is possible. The implementation in QGC is not as good as the implementation in mavproxy.
