### ISSUE TITLE
Frame param file download fails

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/qgroundcontrol#13]
![capture](https://user-images.githubusercontent.com/8315108/27208386-3a33cb78-51fa-11e7-9a3f-40a3485b4c7e.PNG)

**Comment by dheideman** [comment]
Could not reproduce.

Tested on:
 - Early 2015 MacBook Air, OSX 10.10.5, QGC Development pr-rm-record-no-gstream:256fed2
 - Samsung P08AFC, Windows 10 Home Version 1703, QGC Development HEAD:c728d58fa

**Comment by dheideman** [comment]
Error codes are listed here: http://doc.qt.io/qt-5/qnetworkreply.html#NetworkError-enum

**Comment by jaxxzer** [comment]
good.

**Comment by jaxxzer** [comment]
Seen again on Win7: 3.2.4-R1
