### ISSUE TITLE
Add NMEA output for vehicle position

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/qgroundcontrol#148]
On network port.

**Comment by BoKoppel** [comment]
If possible, it would be nice to have NMEA heading as well.
Position and heading might be sent as RMC NMEA sentence?

**Comment by jaxxzer** [comment]
@patrickelectric has done some work on some nice ascii (json) output module in mavproxy [here](https://github.com/bluerobotics/MAVProxy/pull/3).

MAVProxy is the solution for this, everyone will want a certain data and certain format for their specific use case. QGC cannot be made to handle all of the possible use cases.
