### ISSUE TITLE
Text overflow in temperature field on Safety page

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/qgroundcontrol#15]
Observed on Windows 10, font size 8

**Comment by jaxxzer** [comment]
![capture](https://user-images.githubusercontent.com/8315108/27209707-41fd6bae-5202-11e7-96c8-83383e780a2b.PNG)

**Comment by dheideman** [comment]
Addressed in [pr-text-overflow-safety](https://github.com/bluerobotics/qgroundcontrol/tree/pr-text-overflow-safety) branch.

**Comment by dheideman** [comment]
![label wrap](https://user-images.githubusercontent.com/10507633/30397665-7639c05e-9882-11e7-98b4-cb4f06bd14b7.png)
Long labels will be wrapped.

**Comment by jaxxzer** [comment]
https://github.com/mavlink/qgroundcontrol/pull/5660
