### ISSUE TITLE
Error when download parameters

### ISSUE THREAD

**Issue by patrickelectric** [bluerobotics/qgroundcontrol#158]
When using appimage:
Frame→BlueRov2/Vectored→ Load Vehicle Default Parameters →Blue Robotics BlueROV2

FirmwareUpgradeLog: PX4 releases github download failed "Error during download. Error: 99"

@jaxxzer can you confirm this ?

**Comment by jaxxzer** [comment]
Duplicate https://github.com/bluerobotics/qgroundcontrol/issues/13

Are you in a VM?

**Comment by patrickelectric** [comment]
> Are you in a VM?

No, I'm running in my main OS.

**Comment by jaxxzer** [comment]
Can you download firmware?

**Comment by patrickelectric** [comment]
> Can you download firmware?

Yes

**Comment by jaxxzer** [comment]
Well it's apparent that it works in some cases but not others.... We need to find the difference in those cases.

**Comment by patrickelectric** [comment]
With: export QT_LOGGING_RULES="qt.network*.warning=true;qt.network*.debug=true" 
```
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_num_locks
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_set_id_callback
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_set_locking_callback
qt.network.ssl: QSslSocket: cannot resolve ERR_free_strings
qt.network.ssl: QSslSocket: cannot resolve EVP_CIPHER_CTX_cleanup
qt.network.ssl: QSslSocket: cannot resolve EVP_CIPHER_CTX_init
qt.network.ssl: QSslSocket: cannot resolve sk_new_null
qt.network.ssl: QSslSocket: cannot resolve sk_push
qt.network.ssl: QSslSocket: cannot resolve sk_free
qt.network.ssl: QSslSocket: cannot resolve sk_num
qt.network.ssl: QSslSocket: cannot resolve sk_pop_free
qt.network.ssl: QSslSocket: cannot resolve sk_value
qt.network.ssl: QSslSocket: cannot resolve SSL_library_init
qt.network.ssl: QSslSocket: cannot resolve SSL_load_error_strings
qt.network.ssl: QSslSocket: cannot resolve SSL_get_ex_new_index
qt.network.ssl: QSslSocket: cannot resolve SSLv2_client_method
qt.network.ssl: QSslSocket: cannot resolve SSLv3_client_method
qt.network.ssl: QSslSocket: cannot resolve SSLv23_client_method
qt.network.ssl: QSslSocket: cannot resolve SSLv2_server_method
qt.network.ssl: QSslSocket: cannot resolve SSLv3_server_method
qt.network.ssl: QSslSocket: cannot resolve SSLv23_server_method
qt.network.ssl: QSslSocket: cannot resolve X509_STORE_CTX_get_chain
qt.network.ssl: QSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf
qt.network.ssl: QSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf
qt.network.ssl: QSslSocket: cannot resolve SSLeay
qt.network.ssl: QSslSocket: cannot resolve SSLeay_version
qt.network.ssl: QSslSocket: cannot call unresolved function CRYPTO_num_locks
qt.network.ssl: QSslSocket: cannot call unresolved function CRYPTO_set_id_callback
qt.network.ssl: QSslSocket: cannot call unresolved function CRYPTO_set_locking_callback
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_library_init
qt.network.ssl: QSslSocket: cannot call unresolved function SSLv23_client_method
qt.network.ssl: QSslSocket: cannot call unresolved function sk_num
No Internet Access
qt.network.ssl: QSslSocket: cannot call unresolved function SSLv23_client_method
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_library_init
```

It appears to be related with: antony-jr/AppImageUpdater/issues/7

**Comment by jaxxzer** [comment]
@patrickelectric Can you please try `http` instead of `https` here: https://github.com/bluerobotics/qgroundcontrol/blob/3.2.4/src/AutoPilotPlugins/APM/APMAirframeComponentController.cc#L207

**Comment by patrickelectric** [comment]
Good call, will try it.

**Comment by patrickelectric** [comment]
Everything failed.
Will restart the investigations one more time.

**Comment by jaxxzer** [comment]
how about putting on a different host
like s3

**Comment by jaxxzer** [comment]
Any new developments @patrickelectric?

**Comment by patrickelectric** [comment]
The windows problems appears to be solved by: https://github.com/mavlink/qgroundcontrol/pull/6354
The linux problem, as described [here](https://github.com/mavlink/qgroundcontrol/issues/6337) with Don.
The workaround on linux OS that do not use libopenssl-1.0 as default, is to install 1.0 and use `export LD_LIBRARY_PATH=openssl-1.0_path_in_your_system` to set the correct path to search for it.

**Comment by jaxxzer** [comment]
can we cherry-pick the windows fix?

**Comment by patrickelectric** [comment]
yep, they are pretty simple.
I'll create a branch in BR/qgc to test it soon.

**Comment by patrickelectric** [comment]
New windows binary [here](https://ci.appveyor.com/api/buildjobs/fw8ql91npleccltn/artifacts/QGroundControl-installer.exe).
PR based over 3.2.4, https://github.com/bluerobotics/qgroundcontrol/pull/183. Commits are from QGC: https://github.com/mavlink/qgroundcontrol/pull/6354

**Comment by jaxxzer** [comment]
As seen on R6:

![image](https://user-images.githubusercontent.com/8315108/40740028-b1f16c00-6415-11e8-8406-25b3b4d60888.png)

**Comment by patrickelectric** [comment]
Can we test with the original QGC to see if the problem is with our fork ?

**Comment by jaxxzer** [comment]
Yes, but I'm not comfortable asking these particular folks to do that for us. Let's keep it in mind for when this pops up again.

**Comment by patrickelectric** [comment]
We should cherry-pick this:
https://github.com/mavlink/qgroundcontrol/pull/6590

**Comment by jaxxzer** [comment]
@Williangalvani @patrickelectric this one is ok to close?

**Comment by patrickelectric** [comment]
Everything is working fine in upstream.
