### ISSUE TITLE
Surface GPS Use for Subs

### ISSUE THREAD

**Issue by kklemens** [bluerobotics/qgroundcontrol#166]
Current Issue: A conventional GPS module can be used with ArduSub and will have full functionality on the surface. Although not a full underwater positioning system, there is still utility for users when operating on the surface before a dive. However, when the vehicle dives, it loses signal and the position is sent in random directions. 

Recommendation (this may also bleed over into the ArduSub firmware): When the vehicle dives and loses signal, the "GPS Status" will change from either 2 or 3 (fixes) to 1 (GPS detected, but no fix). 

Several things will need to happen:
1. In QGC, have it so the last GPS position is still displayed in the map window, but the vehicle icon will either blink or change color indicating a loss of GPS signal.
2. Still display the vehicle, but at its last fix location. Vehicle yaw orientation will still work and be displayed with the vehicle in map view.
3. Position hold and auto functions will be disabled until a new GPS fix is achieved (vehicle surfaces)

Status, 0 = no GPS, 1 = GPS but no fix, 2 = GPS with 2D fix, 3 = GPS with 3D fix

**Comment by jaxxzer** [comment]
QGC displays the position that the vehicle reports. If the vehicle is reporting some problematic positions when it looses a fix, then it is a firmware issue. This will need to wait until GPS handling is better supported in firmware.

https://github.com/ArduPilot/ardupilot/issues/10845
