### ISSUE TITLE
Remove options for gimbal/lights output according to BRD_PWM_COUNT value

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/qgroundcontrol#169]
Force users into a configuration that will work.

**Comment by patrickelectric** [comment]
BRD_PWM_COUNT should be >= 2 right ?

**Comment by jaxxzer** [comment]
So the idea here is that if BRD_PWM_COUNT = 4, we should only show channels 0-12 as options because they are the only ones with pwm enabled

If BRD_PWM_COUNT = 2, we should only show channels 0-10

And so on.

**Comment by jaxxzer** [comment]
The BRD_PWM_COUNT parameter is allowed to be changed according to the metadata on the parameter.
