### ISSUE TITLE
Add motor test/setup page

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/qgroundcontrol#175]

**Comment by jaxxzer** [comment]
Reopen for upstream

**Comment by jaxxzer** [comment]
Upstream issues:
https://github.com/mavlink/qgroundcontrol/issues/3710
https://github.com/mavlink/qgroundcontrol/issues/3850

MAVLink PR to add proper interface to ardupilot: https://github.com/ArduPilot/mavlink/pull/27

Implement motor test in ArduSub: https://github.com/ArduPilot/ardupilot/pull/8202

**Comment by Williangalvani** [comment]
merged: https://github.com/mavlink/qgroundcontrol/pull/6912
