### ISSUE TITLE
Freeze/Unfreeze Joystick values

### ISSUE THREAD

**Issue by BoKoppel** [bluerobotics/qgroundcontrol#18]
​Keep joystick values in movement Left/Right and Forward/Reverse
You set Your speed/direction manual with joystick.
Those settings is then kept when You press a button and release the joystick.
To get back control, push toggle button again.
Why:
Long movement with same speed. Perfect combined with mode 2 & 3 (Hold heading/hold depth)
Usage during long surveys, long transport sections
Help temporary holding position in currents

**Comment by jaxxzer** [comment]
Hi @BoKoppel, this feature is already built into ArduSub! Assign a button as 'input_hold_toggle' (we use one of the stick push-down buttons). Each time you push the button, the joystick values will be frozen like 'cruise control'.
