### ISSUE TITLE
Display explicitly if firmware connected is running unsupported version

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/qgroundcontrol#191]

**Comment by jaxxzer** [comment]
Notify the user if they are not using the latest stable version, and that some features might not work in this case.

**Comment by jaxxzer** [comment]
https://github.com/mavlink/qgroundcontrol/issues/2797#issuecomment-205563984
relevant!

**Comment by Williangalvani** [comment]
this was done here https://github.com/bluerobotics/qgroundcontrol/pull/210
