### ISSUE TITLE
Graphic of ROV in QGC Map window; more clear heading of icon

### ISSUE THREAD

**Issue by BoKoppel** [bluerobotics/qgroundcontrol#214]
Graphics of ROV on map in QGC, it is hard to see what is bow and stern of the ROV icon.
Could the icon be changed to the same arrow icon as the ship, but blue??
That would also make it easy to program, just copy ship Icon and change colour?

**Comment by jaxxzer** [comment]
I'm open to reconsider if similar reports/complaints arise.
