### ISSUE TITLE
Add support for multicast streams

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/qgroundcontrol#215]

**Comment by jaxxzer** [comment]
The idea here is to allow more than one application to access the video stream on a single udp port.

**Comment by zt-luo** [comment]
> The idea here is to allow more than one application to access the video stream on a single udp port.

why not add more UDP port on companion computer.

**Comment by patrickelectric** [comment]
Duplicate of https://github.com/mavlink/qgroundcontrol/issues/5260.
@zt-luo the problem is in QGC side not companion.
