### ISSUE TITLE
Confirm output framerate

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/qgroundcontrol#217]
per https://discuss.bluerobotics.com/t/framerate-settings/3493

**Comment by Williangalvani** [comment]
It turns out that our camera framerate changes with settings.
A higher exposure correlates to lower frame rate as each frame takes longer to capture.

The framerate can be tested with this pipeline:
```
gst-launch-1.0 -v udpsrc port=5600 caps='application/x-rtp, media=(string)video, clock-rate=(int)90000, encoding-name=(string)H264' \
! rtph264depay \
! avdec_h264 \
! videoconvert \
! fpsdisplaysink
```

**Comment by Williangalvani** [comment]
This has however nothing to do with QGC. It should be in the Companion repository.

**Comment by jaxxzer** [comment]
Interesting! How much does the framerate change, and what do you get with the default settings?

**Comment by Williangalvani** [comment]
framerate indoors is around 15 fps, up to 25 fps if I point my phone flashlight to the lens. The camera is also running quite hot. I'll let it cool and try again.
