### ISSUE TITLE
QGC Crashes on restore from Minimized

### ISSUE THREAD

**Issue by drewfulton** [bluerobotics/qgroundcontrol#220]
On Ubuntu 16.04, I have found that when I am connected to the ROV and viewing the video stream, if I minimize QGC and restore it to the screen the program crashes.  If I am not connected to the ROV, it works just fine.  Running QGC 3.2.4-BlueRobotics-Rev6

**Comment by Williangalvani** [comment]
I tested using a Ubuntu 16.04 VM.
I can replicate it in 3.2.4-Rev6, but it is not present in upstream 3.5.0. Since we'll be moving to that soon, this is not worth fixing here.
