### ISSUE TITLE
Remove record button display when built without gstreamer

### ISSUE THREAD

**Issue by dheideman** [bluerobotics/qgroundcontrol#24]
Record button appears near bottom left of screen when QGroundControl is built without gstreamer installed.

**Comment by jaxxzer** [comment]
nice find!

**Comment by jaxxzer** [comment]
https://github.com/bluerobotics/qgroundcontrol/blob/master/src/FlightDisplay/FlightDisplayView.qml#L365

**Comment by jaxxzer** [comment]
We will need to set the visible property to be conditional on this
https://github.com/bluerobotics/qgroundcontrol/blob/master/src/FlightDisplay/VideoManager.h#L35
