### ISSUE TITLE
Add all Sub modes to supported modes

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/qgroundcontrol#29]
Right now when Sub is in Poshold mode or some others QGC displays 'Unknown' as the mode.

Here are the modes we need to support: https://github.com/ArduPilot/ardupilot/blob/master/ArduSub/defines.h#L33

**Comment by dheideman** [comment]
https://github.com/bluerobotics/qgroundcontrol/tree/pr-add-sub-modes
