### ISSUE TITLE
Altitude should read as Depth

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/qgroundcontrol#3]
This is a little bit too deeply hard-coded right now, but this should be doable after a few more changes following this pull request: https://github.com/mavlink/qgroundcontrol/pull/5121

**Comment by dheideman** [comment]
https://github.com/bluerobotics/qgroundcontrol/tree/pr-sub-specific-fact-description

**Comment by jaxxzer** [comment]
Done here, wait for better implementation upstream. https://github.com/mavlink/qgroundcontrol/pull/5678
