### ISSUE TITLE
Remove camera trigger and vibration pages for Sub vehicles

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/qgroundcontrol#42]

**Comment by dheideman** [comment]
See [pr-rm-instrument-widget-pages](https://github.com/bluerobotics/qgroundcontrol/tree/pr-rm-instrument-widget-pages).

**Comment by jaxxzer** [comment]
This will need to be re-worked to use the new [plugin scheme](https://github.com/mavlink/qgroundcontrol/blob/f11971c/src/api/QGCCorePlugin.cc#L148) in master.

**Comment by jaxxzer** [comment]
Merged, this will work for now. https://github.com/bluerobotics/qgroundcontrol/pull/45

**Comment by jaxxzer** [comment]
We will leave these in upstream unless any issues arise.
