### ISSUE TITLE
Button mapping for Xbox One on Mac is wrong

### ISSUE THREAD

**Issue by rjehangir** [bluerobotics/qgroundcontrol#51]
When connected via bluetooth using the built-in Mac driver, the button mapping for the Xbox One controller is wrong. It probably needs to be added to the button mapping text file. 

See here for the mapping file source:

https://github.com/gabomdq/SDL_GameControllerDB

These files were copied to QGC.

**Comment by jaxxzer** [comment]
https://github.com/bluerobotics/qgroundcontrol/blob/master/resources/SDL_GameControllerDB/gamecontrollerdb.txt

**Comment by dheideman** [comment]
See [pr-update-gamecontrollerdb](https://github.com/bluerobotics/qgroundcontrol/tree/pr-update-gamecontrollerdb)

**Comment by jaxxzer** [comment]
https://github.com/mavlink/qgroundcontrol/pull/5677
