### ISSUE TITLE
Adjust default BROV2 Safety page params to recommended settings

### ISSUE THREAD

**Issue by dheideman** [bluerobotics/qgroundcontrol#75]
The default BROV2 arming checks on the Safety Setup page do not currently reflect the settings usually used in operation.  Only arming checks relevant to normal ROV operation should be set by default.

**Comment by jaxxzer** [comment]
These settings are parameters stored in the autopilot, so this is an ArduSub issue. As of 3.5.1, default checks are: RC, Board Voltage, and Battery Voltage, which I think is appropriate.
