### ISSUE TITLE
Info tab expand from 2 to 4 sometimes

### ISSUE THREAD

**Issue by BoKoppel** [bluerobotics/qgroundcontrol#77]
With new QGC version (3.2.4-BlueRobotics-rev-1) there is 2 info tabs standard since vibration and camera trigger is gone. Sometimes I get 4 tabs, Standard info tab, vehicle Health and 2 more blank tabs.
After a while the 2 extra tabs disappear.
I guess the 2 extra tabs are remains of the old vibration and camera trigger tabs.
No big issue, just a note.

**Comment by dheideman** [comment]
Thanks for pointing this out.

I'll make sure to address this in the rework of #42 to make a better fix for removing the vibration and camera trigger tabs in the instrument widget.
