### ISSUE TITLE
Remove "Fly" toolbar in Flight Display for Sub

### ISSUE THREAD

**Issue by dheideman** [bluerobotics/qgroundcontrol#81]
"Fly" toolbar shows up on left side of screen in flight display page in newest development versions while using ArduSub vehicles.  This should not happen.

**Comment by dheideman** [comment]
Offending commit: https://github.com/mavlink/qgroundcontrol/commit/724df478bf33db742f4cedf5847e84a82077fa71

**Comment by dheideman** [comment]
See [pr-rm-fly-toolbar-sub](https://github.com/bluerobotics/qgroundcontrol/tree/pr-rm-fly-toolbar-sub)

**Comment by jaxxzer** [comment]
This is taken care of.
