### ISSUE TITLE
Disable auto-deleting videos by default

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/qgroundcontrol#83]

**Comment by jaxxzer** [comment]
I think we need two things:

- [ ] disable this by default. It should be opt-in
- [ ] warn/ask the user before deleting anything (maybe lock out the recording button)

**Comment by dheideman** [comment]
See [pr-disk-use-overhaul](https://github.com/bluerobotics/qgroundcontrol/tree/pr-disk-use-overhaul)

**Comment by dheideman** [comment]
[#5693](https://github.com/mavlink/qgroundcontrol/pull/5693)

**Comment by dheideman** [comment]
Reworked according to Don's suggestions in PR #5693.  Waiting on PR #5699.

See [pr-video-limit](https://github.com/bluerobotics/qgroundcontrol/tree/pr-video-limit)

**Comment by jaxxzer** [comment]
Done for BR builds here https://github.com/bluerobotics/qgroundcontrol/pull/91

**Comment by jaxxzer** [comment]
https://github.com/mavlink/qgroundcontrol/pull/5729
