### ISSUE TITLE
Videos deleted if record button is rapidly/repeatedly clicked.

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/qgroundcontrol#86]
http://discuss.bluerobotics.com/t/software-updates-september-14-2017/1491/37

**Comment by dheideman** [comment]
Tested with:
Mac OS X Yosemite
Version 10.10.5
MacBook Air (11-inch, Early 2015)
QGroundControl v3.2.4-BlueRobotics-Rev1

Could not reproduce.
